- name: Pull latest httpd image
  community.docker.docker_image:
    name: 1oooka/tp-devops-httpd:latest
    source: pull
    force_source: true  # force le pull même si latest existe déjà

- name: Remove existing proxy container
  community.docker.docker_container:
    name: proxy
    state: absent

- name: Run HTTPD container
  community.docker.docker_container:
    name: proxy
    image: 1oooka/tp-devops-httpd:latest
    state: started
    restart_policy: always
    networks:
      - name: app_network
    ports:
      - "80:80"
