name: "Phase 4 — Publish Images"

on:
  workflow_run:
    workflows: ["Phase 3 — Build Images"]
    types:
      - completed
    branches:
      - main

jobs:
  push-backend:
    name: "Publish Backend"
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Push backend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-backend:latest
          push: true

  push-database:
    name: "Publish Database"
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Push database Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./database
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest
          push: true

  push-httpd:
    name: "Publish Httpd"
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Push httpd Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./httpd
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
          push: true

  push-front:
    name: "Publish Front"
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Push front Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./front
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-front:latest
          push: true

  deploy:
      name: "Deploy with Ansible"
      needs: [push-backend, push-database, push-httpd, push-front]
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      runs-on: ubuntu-24.04
      environment: production  
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Install Ansible
          run: |
            sudo apt-get update
            sudo apt-get install -y ansible python3-pip
            pip3 install ansible

        - name: Setup SSH key
          run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa_takima
            chmod 600 ~/.ssh/id_rsa_takima
            ssh-keyscan -H antoine.jarmoszko.takima.school >> ~/.ssh/known_hosts

        - name: Deploy with Ansible
          run: ansible-playbook -i ansible/inventories/setup.yml ansible/playbook.yml
