name: CI devops 2025

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-backend:
    runs-on: ubuntu-24.04
    steps:
      # Récupère le code depuis GitHub (fetch-depth 0 pour SonarCloud)
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Installe Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Cache Maven pour accélérer les builds
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Build, teste ET analyse le code avec SonarCloud
      - name: Build, test and analyze with Maven and SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=AntoineSUP_tp-docker -Dsonar.organization=antoinesup -Dsonar.host.url=https://sonarcloud.io --file ./backend/pom.xml

  build-and-push-docker-image:
    needs: test-backend  # se lance UNIQUEMENT si test-backend est vert
    runs-on: ubuntu-24.04
    steps:
      # Récupère le code depuis GitHub
      - name: Checkout code
        uses: actions/checkout@v4

      # Connexion à Docker Hub avec les secrets GitHub
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # Build et push du backend
      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-backend:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      # Build et push de la database
      - name: Build image and push database
        uses: docker/build-push-action@v6
        with:
          context: ./database
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      # Build et push du httpd
      - name: Build image and push httpd
        uses: docker/build-push-action@v6
        with:
          context: ./httpd
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
          push: ${{ github.ref == 'refs/heads/main' }}
